// 常量声明

const types = {
  FETCH_LOADING: "FETCH_LOADING", // loading
  SET_USERINFO: "SET_USERINFO", // SET_USERINFO
  DELETE_USERINFO: "DELETE_USERINFO", // DELETE_USERINFO
  DEL_USERID: "DEL_USERID", // DEL_USERID
  SHOW_LOGINBOX: "SHOW_LOGINBOX", // SHOW_LOGINBOX
  HIDE_LOGINBOX: "HIDE_LOGINBOX", // HIDE_LOGINBOX
  OPEN_MASK: "OPEN_MASK", // OPEN_MASK
  CLOSE_MASK: "CLOSE_MASK", // CLOSE_MASK
  SET_API_LOGIN: "SET_API_LOGIN", // SET_API_LOGIN
  SET_TOKEN: "SET_TOKEN", // SET_TOKEN
  DELETE_TOKEN: "DELETE_TOKEN", // DELETE_TOKEN
  SET_ROUTER_LOGIN: "SET_ROUTER_LOGIN", // SET_ROUTER_LOGIN
  SET_ENCYCLOPEDIA_SELECTED: "SET_ENCYCLOPEDIA_SELECTED", // SET_ENCYCLOPEDIA_SELECTED
  SET_ENCYCLOPEDIA_INDEX: "SET_ENCYCLOPEDIA_INDEX", // SET_ENCYCLOPEDIA_SELECTED
  SET_ISDAYQIANDAO: "SET_ISDAYQIANDAO", // SET_ISDAYQIANDAO
  SET_USERQIANDAOINFOR: "SET_USERQIANDAOINFOR", // SET_USERQIANDAOINFOR
  SET_HASDISABLED: "SET_HASDISABLED", // SET_HASDISABLED
  SET_BOOK_SELECTED: "SET_BOOK_SELECTED", // SET_BOOK_SELECTED
  SET_PLATESTORY_SELECTED: "SET_PLATESTORY_SELECTED", // SET_BOOK_SELECTED
  SET_FUTURESRING_SELECTED: "SET_FUTURESRING_SELECTED", // SET_BOOK_SELECTED
  SET_VIDEOLIST: "SET_VIDEOLIST", // SET_VIDEOLIST
  SET_WATCHLIST: "SET_WATCHLIST" // SET_VIDEOLIST
};

export { types as default };
